### ISSUE TITLE
Opera wallet is not working properly

### ISSUE THREAD

**Issue by sharedStake-main** [blocknative/onboard#480] opened 2021-01-16 14:21 UTC
we are developers from sharedstake.org
App doesn't connect to opera wallet. It is highly possible this is an error on your side.
Outputted error is shown below: 

Uncaught (in promise) Error: infura.io request failed
    at Object.h (index.js:50)
    at h (index.js:540)
    at index.js:285

Thanks!

**Comment by taylorjdawson** [comment] 2021-01-18 19:19
Hi @sharedStake-main! Thank you for bringing this to our attention. Is it possible for you to provide steps to reproduce this error?

**Comment by aaronbarnardsound** [comment] 2021-02-02 23:37
Have tested Opera and it seems to be working correctly with Onboard.js. I am closing this issue due to not receiving more information. Feel free to reopen it if you are still running in to this issue and can give us more details to work with.

**Closed by aaronbarnardsound** 2021-02-02 23:37 UTC
