### ISSUE TITLE
[Bug]: Wallet Select Modal scroll issue

### ISSUE THREAD

**Issue by LucasMoskun** [blocknative/onboard#736] opened 2021-11-03 09:39 UTC
### Current Behavior

I am triggering the wallet select from a button in the middle of my page. When the modal pops up it automatically scrolls me to the top of the page. Is there a way to prevent this behavior?

@aaronbarnardsound Wrote this after looking into the bug:

Hey just had a look in to this and it appears to be a bug in the logic that is designed to lock scrolling when the modal is showing. It listens for scroll events and then automatically sets the scroll position to the top of the page, when it should set the scroll position to the position it was before the modal rendered: https://github.com/blocknative/onboard/blob/525ecb42bb5097f9efcadb18c4ba422550d6ab49/src/views/WalletSelect.svelte#L61

### Expected Behavior

When the modal appears it should center on the screen without scrolling to the top of the page. 

### Steps To Reproduce

1. Add a button to a webpage in the an area that is requires the user to scroll down to access
2. Add wallet select modal pop up functionality to button
3.  Click the button, when the modal appears the page will also scroll to the top. 

### Onboard Version

1.35.1

### Node Version

16.6.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
n/a
```

**Comment by taylorjdawson** [comment] 2021-12-01 00:29
@LucasMoskun Could you provider further context I was unable to reproduce this with our react-demo.

https://user-images.githubusercontent.com/29665732/144149669-1269184a-4946-4bca-8ac5-5a457a16eb5a.mp4

This is in Chrome but same effect in Brave as well

**Comment by taylorjdawson** [comment] 2021-12-06 18:51
@LucasMoskun Bump :)

**Comment by LucasMoskun** [comment] 2021-12-06 20:47
> 

errr sorry, loading up the project now

**Comment by LucasMoskun** [comment] 2021-12-06 21:58
Hmm, updated to the latest packages and still seeing the same issue. I will talk with the other dev and see if we can spot the difference, is this pretty much the same source as what you have in that video? [link](https://github.com/blocknative/react-demo/blob/master/src/App.js)

In the meantime here's some high level snippets showing the integration.
nested div, calling handler onClick:
```
 <div className={`${isConnecting ? 'button-disabled ' : 'button-enabled '}${isConnected ? 'connected-button' : 'connect-button'}`} onClick={onConnectHandler}>
              <img src={`${isConnected ? './assets/images/connected_wallet.gif' : './assets/images/connect_wallet.gif'}`} alt="" />
</div>
```
onConnectHandler
```
const onConnectHandler = () => {
    if(!isConnected && !isConnecting)
    {
      setIsConnecting(true)
      WEB3_CONNECT(setIsConnecting, setIsConnected)
    }
  }
```
WEB3_CONNECT
```
const ConnectWallet = async() => {
    const connected = await onboard.walletSelect();
    //do stuff ..... if connected
}
```

https://user-images.githubusercontent.com/25760403/144929181-d38cc874-67e3-4a1e-a5df-adaf202a5a7e.mov

**Comment by taylorjdawson** [comment] 2021-12-06 22:52
@LucasMoskun is your project oss? Could I pull it for testing?

**Comment by LucasMoskun** [comment] 2021-12-06 23:42
> @LucasMoskun is your project oss? Could I pull it for testing?

Thank you for taking a look :-). Eventually it will be... for now I've thrown up [this temp repo](https://github.com/LucasMoskun/temp_CK) with the branch I'm working on: _LM_release_0_1_0_ 

You will need to add directory src/private and add a file called onboard_api.js with the contents: `export const API_KEY = '_onboard-api-key_';
`
Otherwise yarn install, build should be good to go.

**Comment by taylorjdawson** [comment] 2021-12-08 20:04
@LucasMoskun Excellent I will take a look!

**Comment by taylorjdawson** [comment] 2021-12-08 20:54
@LucasMoskun 

https://user-images.githubusercontent.com/29665732/145282484-0956d997-5ad3-4af4-a045-f4d21140d60c.mp4

This so so strange 🤔 

Specs:
macOS Monterey
Brave: Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (arm64)

What are you running? 

For me [the scroll event callback](https://github.com/blocknative/onboard/blob/525ecb42bb5097f9efcadb18c4ba422550d6ab49/src/views/WalletSelect.svelte#L69) never executes

**Comment by taylorjdawson** [comment] 2021-12-08 21:00
@LucasMoskun Why does your scrollbar look as it does?

**Comment by taylorjdawson** [comment] 2022-01-22 18:03
@LucasMoskun Checking in on this 🙂

**Comment by taylorjdawson** [comment] 2022-01-26 00:47
Closing for now feel free to re-open if issue persists 👍🏾

**Closed by taylorjdawson** 2022-01-26 00:47 UTC
Labels: bug

**Comment by hyetigran** [comment] 2024-05-25 10:35
Issue appears to persist
