### ISSUE TITLE
walletConnect unsupport bsc ?

### ISSUE THREAD

**Issue by h-ping** [blocknative/onboard#564] opened 2021-05-27 07:01 UTC
```
{
          walletName: 'walletConnect',

          preferred: true,

          rpc: { '56': 'https://bsc-dataseed1.defibit.io/' },

          bridge: 'https://bridge.walletconnect.org',
    }
```

**error info:**
![image](https://user-images.githubusercontent.com/10632273/119780035-e7cd6b00-befb-11eb-882b-40bf3ca2a5af.png)

**Comment by taylorjdawson** [comment] 2021-05-28 14:13
Hey @h-ping! Thanks for raising this issue. Which wallet are you using?

**Comment by techgangboss** [comment] 2021-06-03 17:58
Hey @h-ping we are unable to replicate this issue, can you help us replicate? Which wallet are you using? The network acceptance is up to the wallet so please provide more context so we can resolve this issue

**Comment by taylorjdawson** [comment] 2021-06-17 23:13
@h-ping Closing as stale for now. Please feel free to re-open if the issue persists.

**Comment by roy1210** [comment] 2021-07-23 13:21
Hi @taylorjdawson 

I'm seeing the same issue when set as:
```
Onboard({
    dappId: blocknativeApiKey,
    networkId,
    hideBranding: true,
    subscriptions,
    walletSelect: {
      wallets: [
        {
          walletName: 'walletConnect',
          preferred: true,
          rpc: { '56': 'https://bsc-dataseed1.defibit.io/' },
          bridge: 'https://bridge.walletconnect.org',
        },
      ],
    },
    walletCheck: [
      { checkName: 'derivationPath' },
      { checkName: 'connect' },
      { checkName: 'accounts' },
      { checkName: 'network' },
      { checkName: 'balance', minimumBalance: '100000' },
    ],
  });
```

I have tried another RPC URL 'https://bsc-dataseed1.binance.org:443', but the same result. 
Looks like onboard take it as `network Id = 1` somehow.

![image](https://user-images.githubusercontent.com/42575132/126787112-00053b28-4c05-4754-b70f-b3604bd35283.png)

**Comment by taylorjdawson** [comment] 2021-07-23 18:59
@roy1210 A few questions:
1. What version of onboard are you using?
2. Is `networkId` in your onboard init object set to `56`?
3. Which wallet are you using?


I just tested and saw no issues, here is what I did. Note I used the [react-demo](https://github.com/blocknative/react-demo) for testing this.
- I took your example and I placed this into my onboard init object
```js
        {
          walletName: 'walletConnect',
          preferred: true,
          rpc: { '56': 'https://bsc-dataseed1.defibit.io/' },
          bridge: 'https://bridge.walletconnect.org',
        },
```
- Then I set my `networkId` to `56`
- Next I started up the react-demo and selected walletconnect
- Then I clicked the Wallet Check button and the walletconnect QR code appeared
- I opened my Metamask Mobile wallet and set the network to Binance Smart Chain
- Next I scaneed the QR code with my Metamask Mobile wallet
- Then after a moment I saw that the react demo showed the same address as in Metamask Mobile and the console showed no errors

If I am missing something let me know, thanks! 👍🏾

**Comment by roy1210** [comment] 2021-07-24 02:54
Hi @taylorjdawson 

1 > 1.30.0
2 > yes
3 > Trustwallet

I have forked your demo app and changed config like [this](https://github.com/roy1210/react-demo/blob/fix/add-bsc-config/src/services.js).
But Trustwallet still connects to `networkId = 1`. I think that is the Trustwallet app doesn't have changing network feature as Metamask Mobile has. But instead, wallet connect has the ability to set the `chainId`. And if you have used 'Pancake swap', pancake swap supports BSC for Trustwallet as default :D 

Ref
https://docs.walletconnect.org/tech-spec#session-request
https://github.com/trustwallet/wallet-core/issues/1290
https://github.com/pancakeswap/pancake-frontend/blob/efd2288e0169434b1c9a4e5541f043016b58ad05/src/utils/web3React.ts#L14
 
![image](https://user-images.githubusercontent.com/42575132/126855302-ac67ddee-0a4c-4763-93df-969bc3b7b62e.png)

**Comment by roy1210** [comment] 2021-07-24 17:35
Hey @taylorjdawson 
I have made `WalletConnect BSC` custom module and it works great in my project. 
You can find my code in [here](https://gist.github.com/roy1210/e5617e820202bc4f27fc28d7c4dba101) :D You may close this issue, thanks!

![image](https://user-images.githubusercontent.com/42575132/126876547-9597e99d-b2ba-46ac-b315-101eb6c6f17c.png)

**Comment by roy1210** [comment] 2021-07-24 17:41
Btw, looks like `custom moudle` only works for v.1.27.0. UI won't show custom modules if above than v.1.27.0.
(I have done `rm -rf node_modules` then restart my laptop before run `yarn dev` to make it works.)

node: v14.17.3
"next": "^10.1.3",
"react": "^17.0.2",
"react-dom": "17.0.1",

**Comment by taylorjdawson** [comment] 2021-07-28 01:50
@roy1210 Does your custom walletconnect BSC module work with Trust wallet? Also try updating to v1.31 of Onboard I am able to get custom wallet modules to work no issue. Here is a [demo](https://codesandbox.io/s/onboard-custom-wallet-demo-jekzo) of doing such.

**Comment by roy1210** [comment] 2021-07-28 07:13
@taylorjdawson 

> Does your custom walletconnect BSC module work with Trust wallet? 
Yes! This is my dApps URL. https://farm.swingby.network/ I'm using V1.27.0. It works without any issue!

>  Also try updating to v1.31
Just updated to v1.31, It looks like able to chose 'custom module' but the app can't be scrolled after chose `WalletConnect`. Not sure the issue is on v.1.31 or my app.
demo (v.1.31) : https://yield-farming-7pmhdg1um-swingby.vercel.app/

**Comment by roy1210** [comment] 2021-08-09 14:19
Hi @taylorjdawson 
I got this error when choose 'WalletConnect'. This error makes disable the scroll down.
It would be appreciated if you have can advice about this error. Thanks!

Version: 1.27.0 and 1.33.0

![image](https://user-images.githubusercontent.com/42575132/128720988-30142b95-9c04-4794-8435-487f26031215.png)
![image](https://user-images.githubusercontent.com/42575132/128721048-02c468ee-8de7-43ad-88f2-c9743fb9f85e.png)
![image](https://user-images.githubusercontent.com/42575132/128721251-166073be-667f-4783-bbc2-0ed9735d6411.png)

**Comment by taylorjdawson** [comment] 2021-08-13 19:58
@roy1210 I have included BSC wallet in the latest release.
@h-ping I was able to connect to BSC via WalletConnect and Metamask using v1.34.0 of Onboard.

Please re-open if any of these issues persist, thanks!

**Closed by taylorjdawson** 2021-08-13 19:58 UTC
