### ISSUE TITLE
WalletConnect: Add chainId option

### ISSUE THREAD

**Issue by PeterTheOne** [blocknative/onboard#471] opened 2020-12-21 13:03 UTC
WalletConnect has the option to tell the wallet which network should connect by sending the chainId with the wc_sessionRequest request. onboard.js doesn't provide the option to pass the chainId to WalletConnect.

**Comment by tze42** [comment] 2020-12-25 09:33
@aaronbarnardsound we would love to stick to onboard.js for the ZeroAlpha.art NFT platform and need the option to set the ChainID for WalletConnect. I hope you find time to look at it and give us an estimate if you plan to do something on that in the short term.

**Comment by aaronbarnardsound** [comment] 2021-01-26 04:35
Hey @PeterTheOne @tze42 I am looking at the [WalletConnect Web3 Provider](https://docs.walletconnect.org/quick-start/dapps/web3-provider#provider-options) docs and I don't see an option to pass in a `chainId`?

**Comment by PeterTheOne** [comment] 2021-02-01 08:51
Unfortunately web3-provider also doesn't seem to have an option for that. :( But the WalletConnect core and [web3modal](https://github.com/Web3Modal/web3modal) for example have it.

**Comment by aaronbarnardsound** [comment] 2021-02-02 23:44
Hey @PeterTheOne could you explain your use case for passing in the `chainId` to WalletConnect a little more? Does passing it in inform the mobile wallet to switch to that network automatically without the need for user input? 

By setting the `networkId` property when initializing Onboard, it will ensure the user is connected to that network via the `network` wallet check module when `onboard.walletCheck()` is called. Hopefully that helps with your usecase.

**Comment by PeterTheOne** [comment] 2021-02-03 16:16
@aaronbarnardsound Exactly, the dapp tells the wallet what network it should use. This is far better UX than the other way around as MetaMask does it. There are wallets that have more than one network active at the same time (Trustwallet, alphawallet, Minerva wallet) and they need to know to which network the walletconnect connection belongs to. Of course the user could point to the correct network manually if he/she knew but automatic would be better.

**Comment by aaronbarnardsound** [comment] 2021-02-18 00:24
@PeterTheOne Ok no worries, that makes sense and thanks for the feedback. I will do some digging to see how we could use WalletConnect core instead of the web3-provider.

**Comment by PeterTheOne** [comment] 2021-04-22 08:40
Btw. our friends at SuperFluid added another UI to choose a network in their dapp that I really like:

![photo604645747c2320910968](https://user-images.githubusercontent.com/666289/115683671-fa7dde80-a356-11eb-8e82-1c483cb0d102.jpg)

**Comment by PeterTheOne** [comment] 2021-04-22 08:43
Our Android Wallet [Minerva](https://minerva.digital/) throws an error if the wrong chainId is send to prevent the user from creating transactions on the wrong network.

**Comment by sp1r1don** [comment] 2021-05-04 21:17
Hello guys! I'm from Component team. I'm here because @PeterTheOne mentioned us in his tweet. We using onboard as wallet connection tool. So we have a trouble with WalletConnect on xdai chain. I set those settings:
`
walletSelect: {
  ...
  networkId: 100,
  wallets: [
    { walletName: "metamask", preferred: true },
    {
      walletName: "walletConnect",
      preferred: true,
      rpc: { 100: config.defaultWeb3Provider },
      bridge: 'https://bridge.walletconnect.org',
    },
  ]
}
`

**Comment by taylorjdawson** [comment] 2021-05-04 21:19
Hey @sp1r1don! Could you elaborate on what issues you're having with xdai chain and `walletConnect`?

**Comment by sp1r1don** [comment] 2021-05-04 21:58
Hi @taylorjdawson! When I trying to connect, for example Minerva wallet via walletConnect, I got an error, `You need to initiate this WalletConnect session from an account on the Ethereum for this website`. And it shows that walletConnect use mainnet instead of xdai network

**Comment by sp1r1don** [comment] 2021-05-04 22:15
I don't know exactly what the problem is...

**Comment by taylorjdawson** [comment] 2021-05-05 00:13
@sp1r1don When you say that it is using `mainnet` instead of `xdai` do you mean it is using `ethereum mainnet` instead of `xdai mainnet`?

**Comment by sp1r1don** [comment] 2021-05-05 07:55
@taylorjdawson Yeah, seems like that

**Comment by tze42** [comment] 2021-05-05 17:33
@sp1r1don we will try to make it work for Component on xDai Chain, but it would be way better if the problem wouldn't be there in the first place. For AlphaWallet it will not work. 
Gnosis solved it in this way: https://github.com/gnosis/ido-ux/pull/493/files#diff-7f6c45fbb62ba89e3f44e887c2180a4fad9cd98ca0c9661d39252be2d426a618R46-R51

**Comment by taylorjdawson** [comment] 2021-05-05 17:41
Just to clarify, while onboard's method params and init object says `networkId` if the wallet you're using uses a `chainId` then onboard will pass the `networkId` to the wallet as the `chainId`.

**Comment by tze42** [comment] 2021-05-05 17:49
For xDai Chain both are 100, but we get 1 (for Ethereum) sent to the wallet.

**Comment by taylorjdawson** [comment] 2021-05-05 17:50
@tze42 So you're saying that in your onboard.js config you set `networkId: 100` but then `1` is what actually get's passed to WalletConnect?

**Comment by tze42** [comment] 2021-05-05 17:54
I'm refering to @sp1r1don and how he described it above. What we get in the Minerva Wallet is `1` if we try to connect an xDai Chain account via WalletConnet to https://xdai.component.finance/

**Comment by sp1r1don** [comment] 2021-05-05 18:55
> I'm refering to @sp1r1don and how he described it above. What we get in the Minerva Wallet is `1` if we try to connect an xDai Chain account via WalletConnet to https://xdai.component.finance/

We have same issue

**Comment by taylorjdawson** [comment] 2021-05-06 14:11
@tze42 is this an onboard.js issue or is it related to WalletConnect/Minerva wallet?

**Comment by tze42** [comment] 2021-05-06 17:34
It is for sure not Minerva Wallet and looking at @sp1r1don config, I would not see why this should't work as we would expect it. 
So in short, yes, I believe it is onboard.js. I somehow ignores the configuration for chainId: 100 and maybe also other chainId's.

> networkId: 100,
>   wallets: [
>     { walletName: "metamask", preferred: true },
>     {
>       walletName: "walletConnect",
>       preferred: true,
>       rpc: { 100: config.defaultWeb3Provider },
>       bridge: 'https://bridge.walletconnect.org',

**Comment by taylorjdawson** [comment] 2021-05-10 18:16
@tze42 okay I'll look into this, this week. Could you provide some repro steps that would help speed up the process on my end. At very least could you provide the complete onboard.js config? 

From the looks of if I'll just need to config onboardjs the same way you showed, then try and connect to Minerva via wallet connect?

**Comment by taylorjdawson** [comment] 2021-05-23 20:55
- Go to [xdai.component.finance](https://xdai.component.finance/)
- Select "WalletConnect" from the onboard.js modal
- The QR code pops up, I click "Copy to clipboard"
- Go to [test.walletconnect.org](https://test.walletconnect.org/) select xDAI Chain in the Network drop down then paste in the `wc: uri` that was just copied
- Modal now shows "Component xDai" click "Approve" and then go back to xdai.component.finance
- I see a loading spinner and see error messages in the console
![image](https://user-images.githubusercontent.com/29665732/119275984-0adede80-bbcd-11eb-994c-a33dfa5d8ef8.png)
- Next I check the local storage for the `walletconnect` key and I see this in the value field:
<details>
<summary>Expand to see full json object</summary>

```
{
  "connected": true,
  "accounts": [
    "0x041A788d22668d68d7723c2731B1BcA664393592"
  ],
  "chainId": 100,
  "bridge": "https://bridge.walletconnect.org",
  "key": "3cbb7a812ba3363d53f77e104de30be9c9a30f58082e0434b4e1b98af761b0b2",
  "clientId": "f084eafb-5531-4f36-9fc9-6ee184c10ad2",
  "clientMeta": {
    "description": "Flexible AMM protocol",
    "url": "https://xdai.component.finance",
    "icons": [
      "https://xdai.component.finance/favicon.ico",
      "https://xdai.component.finance/logo.png"
    ],
    "name": "Component xDai"
  },
  "peerId": "301da88f-c613-4940-9c3c-674422c1c5c7",
  "peerMeta": {
    "description": "",
    "url": "https://test.walletconnect.org",
    "icons": [
      "https://test.walletconnect.org/favicon.ico",
      "https://test.walletconnect.org/apple-touch-icon.png"
    ],
    "name": "WalletConnect Test Wallet"
  },
  "handshakeId": 1621802578702879,
  "handshakeTopic": "4b62e079-1c44-4653-8cab-b28fdeb8db36"
}
```
</details>

This indicates to me that everything seems to be working properly as WalletConnect has the right `chainId` set as seen above.

I will note that I was unable to connect to xdai.component.finance via Minerva wallet.

If you have another set of repros steps that produces a different outcome and I'll try it

**Comment by taylorjdawson** [comment] 2021-06-03 17:54
Checking in on this @tze42 @PeterTheOne @sp1r1don ^^

**Comment by tze42** [comment] 2021-06-08 14:38
Hi @taylorjdawson 
I guess we will have to wait for @sp1r1don. We will focus on other WalletConnect DApp integrations in the meantime.

**Comment by taylorjdawson** [comment] 2021-06-08 18:05
@tze42 Okay sounds good, let me know if there is anything on the onboard.js side that we can do.

**Comment by angrywasp** [comment] 2021-07-03 14:14
> * Go to [xdai.component.finance](https://xdai.component.finance/)
> * Select "WalletConnect" from the onboard.js modal
> * The QR code pops up, I click "Copy to clipboard"
> * Go to [test.walletconnect.org](https://test.walletconnect.org/) select xDAI Chain in the Network drop down then paste in the `wc: uri` that was just copied
> * Modal now shows "Component xDai" click "Approve" and then go back to xdai.component.finance
> * I see a loading spinner and see error messages in the console
>   ![image](https://user-images.githubusercontent.com/29665732/119275984-0adede80-bbcd-11eb-994c-a33dfa5d8ef8.png)
> * Next I check the local storage for the `walletconnect` key and I see this in the value field:
> 
> Expand to see full json object
> This indicates to me that everything seems to be working properly as WalletConnect has the right `chainId` set as seen above.
> 
> I will note that I was unable to connect to xdai.component.finance via Minerva wallet.
> 
> If you have another set of repros steps that produces a different outcome and I'll try it

The chain is appears right here because that is the chain id returned from the wallet connect test wallet. try the same thing again while selecting any network that is not xdai. 

In any case, unless i am missing something obvious, it appears to be confirmed. Using this configuration

```JS
    var onboard = Onboard({
        dappId: "<redacted>",
        networkId: 56,
        networkName: "BSC Mainnet",
        walletSelect: {
            wallets: [
                {
                    walletName: "walletConnect",
                    rpc: {
                        [1]: "https://mainnet.infura.io/v3/9354d2b6c5ee45c2a4036efd7b617783",
                        [56]: "https://bsc-dataseed.binance.org/"
                    },
                    networkId: 56
                }
            ]
        },
        subscriptions: {
            address: address => {
                console.log(address);
            },
            network: network => {
                console.log(network);
            },
            wallet: wallet => {
                console.log(wallet);
            }
        }
    });
```

My app on the other end receives this JSON. The ChainID is set to 1, even though i have set it to 56 in the web dapp

```JSON
{
    "id":1625320902519566,
    "jsonrpc":"2.0",
    "method":"wc_sessionRequest",
    "params":[
       {
          "peerId":"945965aa-01a2-48e9-914c-0f6921e4ef20",
          "peerMeta":{
             "description":"",
             "url":"http://localhost:3000",
             "icons":[
                "http://localhost:3000/logo512.png"
             ],
             "name":"Web App"
          },
          "chainId":1
       }
    ]
 }
 ```

Use case is quite simple. I have build a multichain wallet and this chain id is required to be provided  so the wallet can process transactions on the correct chain without user intervention to select a matching network.

**Comment by taylorjdawson** [comment] 2021-07-09 19:31
@angrywasp Just to clarify when you say "My app on the other end receives this JSON." by "app" you mean your wallet right?

**Comment by taylorjdawson** [comment] 2021-07-09 19:37
@angrywasp I tried it with Ropsten and the ChainID matched. Can you outline repro steps so I can debug? Thanks 👍🏾

**Comment by taylorjdawson** [comment] 2021-07-22 18:05
@angrywasp @tze42 @sp1r1don Could one of you please open a new issue as this is not related to the `Add chainId option`.
Please include detailed repro steps showing that onboard indeed is sending the wrong chainId.

Closing for now as `networkId` does get passed to WalletConnect as `chainId`

**Closed by taylorjdawson** 2021-07-22 18:05 UTC

**Comment by taylorjdawson** [comment] 2021-09-30 18:55
@angrywasp @tze42 @sp1r1don @PeterTheOne 
So it turns out that there was an issue with WalletConnect not getting the chainId! Apologies for not fully understanding the problem. This will be fixed in #714

**Comment by taylorjdawson** [comment] 2021-09-30 18:57
(See #711)

**Comment by vijaynextazy** [comment] 2022-02-28 04:29
> > * Go to [xdai.component.finance](https://xdai.component.finance/)
> > * Select "WalletConnect" from the onboard.js modal
> > * The QR code pops up, I click "Copy to clipboard"
> > * Go to [test.walletconnect.org](https://test.walletconnect.org/) select xDAI Chain in the Network drop down then paste in the `wc: uri` that was just copied
> > * Modal now shows "Component xDai" click "Approve" and then go back to xdai.component.finance
> > * I see a loading spinner and see error messages in the console
> >   ![image](https://user-images.githubusercontent.com/29665732/119275984-0adede80-bbcd-11eb-994c-a33dfa5d8ef8.png)
> > * Next I check the local storage for the `walletconnect` key and I see this in the value field:
> > 
> > Expand to see full json object
> > This indicates to me that everything seems to be working properly as WalletConnect has the right `chainId` set as seen above.
> > I will note that I was unable to connect to xdai.component.finance via Minerva wallet.
> > If you have another set of repros steps that produces a different outcome and I'll try it
> 
> The chain is appears right here because that is the chain id returned from the wallet connect test wallet. try the same thing again while selecting any network that is not xdai.
> 
> In any case, unless i am missing something obvious, it appears to be confirmed. Using this configuration
> 
> ```js
>     var onboard = Onboard({
>         dappId: "<redacted>",
>         networkId: 56,
>         networkName: "BSC Mainnet",
>         walletSelect: {
>             wallets: [
>                 {
>                     walletName: "walletConnect",
>                     rpc: {
>                         [1]: "https://mainnet.infura.io/v3/9354d2b6c5ee45c2a4036efd7b617783",
>                         [56]: "https://bsc-dataseed.binance.org/"
>                     },
>                     networkId: 56
>                 }
>             ]
>         },
>         subscriptions: {
>             address: address => {
>                 console.log(address);
>             },
>             network: network => {
>                 console.log(network);
>             },
>             wallet: wallet => {
>                 console.log(wallet);
>             }
>         }
>     });
> ```
> 
> My app on the other end receives this JSON. The ChainID is set to 1, even though i have set it to 56 in the web dapp
> 
> ```json
> {
>     "id":1625320902519566,
>     "jsonrpc":"2.0",
>     "method":"wc_sessionRequest",
>     "params":[
>        {
>           "peerId":"945965aa-01a2-48e9-914c-0f6921e4ef20",
>           "peerMeta":{
>              "description":"",
>              "url":"http://localhost:3000",
>              "icons":[
>                 "http://localhost:3000/logo512.png"
>              ],
>              "name":"Web App"
>           },
>           "chainId":1
>        }
>     ]
>  }
> ```
> 
> Use case is quite simple. I have build a multichain wallet and this chain id is required to be provided so the wallet can process transactions on the correct chain without user intervention to select a matching network.

Go to local Storage remove wallet connection previous wallet address and connect again
